conversation_directories:
  LLM_output: output/LLM_output
  user_query_analyze_path: output/LLM_output/analyze
  user_query_retrieval_filtered_path: output/LLM_output/retrieve/user_query_retrieve_filtered_result
  user_query_retrieval_filtered_split_path: output/LLM_output/retrieve/split_filtered_result
  user_query_retrieval_save_path: output/LLM_output/retrieve/user_query_retrieve_result
directories:
  apk_info_dir: output/APK_info.txt
  java_dir: output/reversedAPK/sources
  reversed_apk_dir: output/reversedAPK
env:
  LANGCHAIN_API_KEY: dummy
  LANGCHAIN_ENDPOINT: dummy
  LANGCHAIN_TRACING_V2: 'false'
  jadx_bat: jadx-1.5.1/bin/jadx
  jadx_bin: jadx-1.5.1/bin
  openai_api_key: sk-local
llm:
  base_url: http://localhost:5001/v1
  base_url_embedding: http://localhost:5002/v1
  cleaning_model: gpt-4o-2024-11-20
  embedding_model: text-embedding-ada-002
  model_name: gpt-4o
  model_o3_mini: o3-mini
  summary_model: gpt-4o-2024-11-20
  temperature: 0
openai:
  api_key: sk-local
qdrant:
  api_key: dummy
  collection_name: 7ADD3CCC0D78FA94B28A5297ED80237C9CADA9405EB061D0F09F0044DA503218
  retrieve_num_limit: 20
  url: http://localhost:6333
weaviate:
  api_key: dummy
  distance: 0.25
  index_name: TEST_000C5A8A35C55183A4718192E328E68B44D5457AA99E37F39B2B1AA16644E8FD
  retrieve_num_limit: 5
  url: dummy
